{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ldap-tls-slave
  labels:
    app: {{ template "openldap.name" . }}-slave
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.files.slave.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.tls.files.slave.tlsKey | b64enc | quote }}
  ca.crt: {{ .Values.tls.files.slave.caCrt | b64enc | quote }}
  dhparam.pem: {{ .Values.tls.files.slave.dhparamPem | b64enc | quote }}
{{ end }}
