apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}-headless-slave
  labels:
    app: {{ template "openldap.fullname" . }}-slave
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.service.ldapPort }}
    name: ldap-port
    targetPort: ldap-port
  clusterIP: None
  selector:
    app: {{ template "openldap.fullname" . }}-slave
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
